"""empty message

Revision ID: 27a07f75946a
Revises: 617195671b71
Create Date: 2021-02-24 23:24:24.124785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27a07f75946a'
down_revision = '617195671b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('user', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`done` in (0,1))', name='tasks_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user', 'tasks', ['user'], unique=True)
    op.drop_table('todo')
    # ### end Alembic commands ###
